// <auto-generated />
using DwComment.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace DwComment.Migrations
{
    [DbContext(typeof(DwCommentContext))]
    [Migration("20171205043918_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("DwComment.Models.Comment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired();

                    b.Property<long>("ForwardTo");

                    b.Property<string>("Link");

                    b.Property<string>("Mail");

                    b.Property<string>("Nickname")
                        .IsRequired();

                    b.Property<int>("ThreadId");

                    b.Property<long>("Time");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.ToTable("Comment");
                });
#pragma warning restore 612, 618
        }
    }
}
